feat(ci): migrate to just, pt1

diff --git a/.archived/taskfiles/talos/Taskfile.yaml b/.archived/taskfiles/talos/Taskfile.yaml
--- a/.archived/taskfiles/talos/Taskfile.yaml
+++ b/.archived/taskfiles/talos/Taskfile.yaml
@@ -2,113 +2,82 @@
 # yaml-language-server: $schema=https://taskfile.dev/schema.json
 version: "3"
 
-# : 'talhelper-less' talos bootstrap tasks
-# :: folder structure
-# ./infrastructure/talos/{controlplane-'nodename',controlplane,schematic}.yaml.j2; extraManifests in controlplane.yaml.j2;
-
-vars:
-  SYSTEM_UPGRADE_KS: "{{.K8S_DIR}}/apps/gitops-system/system-upgrade-controller/ks.yaml"
-env:
-  KUBERNETES_VERSION:
-    sh: yq '.spec.postBuild.substitute.KUBERNETES_VERSION | select(.)' {{.SYSTEM_UPGRADE_KS}}
-  TALOS_VERSION:
-    sh: yq '.spec.postBuild.substitute.TALOS_VERSION | select(.)' {{.SYSTEM_UPGRADE_KS}}
-
 tasks:
-  ## :: replace 'bootstrap:talos'
-  talos:
-    desc: Bootstrap Talos
-    vars:
-      MODE: '{{.MODE | default "prod"}}'
-      RANDOM_CONTROLLER:
-        sh: talosctl config info --output json | jq --raw-output '.endpoints[]' | shuf -n 1
-      K8S_CONTEXT: '{{.K8S_CONTEXT | default "main"}}'
-      K8S_ENDPOINT: '{{.K8S_ENDPOINT | default "https://k8s.homelab.internal:6443"}}'
-    preconditions:
-      - which bash jq kubectl talosctl
-      - talosctl config info
-    cmds:
-      - task: talos:_bootstrap MODE={{.MODE}}
-      - until talosctl --nodes {{.RANDOM_CONTROLLER}} bootstrap; do sleep 5; done
-      - kubectl config set-cluster {{.K8S_CONTEXT}} --server {{.K8S_ENDPOINT}}
-      - talosctl kubeconfig --nodes {{.RANDOM_CONTROLLER}} --force ${KUBECONFIG}
-      - bash -c 'mkdir -p ~/.kube && cp ${KUBECONFIG} ~/.kube/config'
-
-  ## :: replace 'talos:generate'
-  generate:
-    desc: Generate/Refresh Talos client configuration
-    preconditions:
-      - which op talosctl
-      - op user get --me
-    cmds:
-      - op item get talos --fields label=machine_ca_crt --reveal | base64 -d > ca.crt
-      - op item get talos --fields label=machine_ca_key --reveal | base64 -d > ca.key
-      - talosctl gen key --name admin
-      - talosctl gen csr --key admin.key --ip 127.0.0.1
-      - talosctl gen crt --ca ca --csr admin.csr --name admin --force --hours 8760
-      - |
-        cat <<EOF > talosconfig
-        context: admin@main
-        contexts:
-          admin@main:
-            ca: $(base64 ca.crt | tr -d '\n')
-            crt: $(base64 admin.crt | tr -d '\n')
-            key: $(base64 admin.key | tr -d '\n')
-        EOF
-      - rm -f ca.crt ca.key admin.key admin.csr admin.crt
-      - mv -f talosconfig ${TALOSCONFIG}
-      - bash -c 'mkdir -p ~/.talos && cp ${TALOSCONFIG} ~/.talos/config'
-
-  ## :: add to 'talos:'
-  apply-node:
-    desc: Apply Talos config for a node [NODE=required]
-    vars:
-      DRYRUN: '{{.DRYRUN | default "false"}}'
-      INSECURE:
-        sh: talosctl --nodes {{.NODE}} get machineconfig &> /dev/null || echo true
-      MACHINE_TYPE: '{{.MACHINE_TYPE | default "controlplane"}}'
-      MODE: '{{.MODE | default "prod"}}'
-    requires:
-      vars:
-        - NODE
+  getimage:
+    desc: Get latest ISO for talos
+    silent: true
     preconditions:
       - '[[ "{{.MODE}}" == "test" || "{{.MODE}}" == "prod" ]]'
-      - which curl jq minijinja-cli op talosctl
-      - test -f {{.TALOS_DIR}}/schematic.yaml.j2
-      - test -f {{.TALOS_DIR}}/{{.MACHINE_TYPE}}.yaml.j2
-      - test -f {{.TALOS_DIR}}/{{.MACHINE_TYPE}}-{{.NODE}}.yaml.j2
-      - talosctl config info
-      - op user get --me
-    env:
-      MODE: "{{.MODE}}"
-      TALOS_SCHEMATIC:
+      - '[[ "{{.SECUREBOOT}}" == "true" || "{{.SECUREBOOT}}" == "false" ]]'
+      - which curl jq yq
+      - test -f "{{.TALOS_DIR}}/talconfig.{{.MODE}}.yaml"
+    vars:
+      MODE: '{{.MODE | default "prod"}}'
+      ARCH: '{{.ARCH | default "amd64"}}'
+      PLATFORM: '{{.PLATFORM | default "metal"}}'
+      SECUREBOOT: '{{.SECUREBOOT | default "true"}}'
+      VERSION:
+        sh:
+          curl --silent --noproxy '*' https://factory.talos.dev/versions | jq --raw-output '
+          map(select(test("^v[0-9.]+$"))) | sort_by(. | ltrimstr("v") | split(".") | map(tonumber)) | reverse | .[0]' | tail -n1
+      ID:
         sh: |
-          MODE={{.MODE}} minijinja-cli {{.TALOS_DIR}}/schematic.yaml.j2 \
-            | curl --silent --noproxy '*' -X POST --data-binary @- https://factory.talos.dev/schematics \
-            | jq --raw-output '.id'
-    cmd: |
-      minijinja-cli {{.TALOS_DIR}}/{{.MACHINE_TYPE}}.yaml.j2 \
-        | op inject \
-        | talosctl --nodes {{.NODE}} apply-config \
-          --config-patch @<(minijinja-cli {{.TALOS_DIR}}/{{.MACHINE_TYPE}}-{{.NODE}}.yaml.j2) \
-          --file /dev/stdin {{if (eq .INSECURE "true")}}--insecure{{end}} {{if (eq .DRYRUN "true")}}--dry-run{{end}}
+          yq '.controlPlane.schematic' "{{.TALOS_DIR}}/talconfig.{{.MODE}}.yaml" > /tmp/schematic.yaml
+          curl --silent --noproxy '*' -X POST --data-binary @/tmp/schematic.yaml https://factory.talos.dev/schematics | jq --raw-output '.id'
+      IMAGE: '{{.PLATFORM}}-{{.ARCH}}{{if (eq .SECUREBOOT "true")}}-secureboot{{end}}.iso'
+    cmds:
+      - |
+        echo "Latest version: {{.VERSION}}"
+        echo "Schema ID: {{.ID}}"
+        echo "Image Downloading: talos-{{.VERSION}}-{{.IMAGE}}"
+        curl --progress-bar -L "https://factory.talos.dev/image/{{.ID}}/{{.VERSION}}/{{.IMAGE}}" -o /tmp/talos-{{.VERSION}}-{{.MODE}}-{{.IMAGE}} || (echo "Download failed"; exit 1)
+      - mv /tmp/talos-{{.VERSION}}-{{.MODE}}-{{.IMAGE}} ./
 
-  # :: replace 'talos:_bootstrap', remove 'talos:_apply-machineconfig'
+  generate:
+    desc: Generate bootstrap configs for talos cluster
+    silent: true
+    preconditions:
+      - '[[ "{{.MODE}}" == "test" || "{{.MODE}}" == "prod" ]]'
+      - which op talhelper
+      - test -f "{{.TALOS_DIR}}/talconfig.{{.MODE}}.yaml"
+      - test -f "{{.TALOS_DIR}}/talsecret.yaml"
+      - test -f "{{.TALOS_DIR}}/talhelper.env"
+      - op user get --me
+    vars:
+      MODE: '{{.MODE | default "prod"}}'
+    cmds:
+      - op run --env-file {{.TALOS_DIR}}/talhelper.env --no-masking -- talhelper genconfig
+        --config-file {{.TALOS_DIR}}/talconfig.{{.MODE}}.yaml
+        --secret-file {{.TALOS_DIR}}/talsecret.yaml
+        --out-dir {{.TALOS_DIR}}/clusterconfig
+      - bash -c 'mkdir -p ~/.talos && cp ${TALOSCONFIG} ~/.talos/config'
+
   _bootstrap:
     internal: true
     desc: Apply bootstrap configs to talos cluster
     silent: true
     vars:
-      MODE: '{{.MODE | default "prod"}}'
       FILES:
-        sh: ls {{.TALOS_DIR}}/*.yaml.j2
+        sh: ls {{.TALOS_DIR}}/clusterconfig/*.yaml
     cmds:
-      # bootstrap controlplane nodes
       - for:
           var: FILES
-        task: apply-node
+        task: _apply-machineconfig
         vars:
-          MODE: "{{.MODE}}"
-          MACHINE_TYPE: "controlplane"
-          NODE: |-
-            {{ trimPrefix (printf "controlplane-") (base .ITEM) | trimSuffix ".yaml.j2" }}
+          FILENAME: "{{.ITEM}}"
+          HOSTNAME: |-
+            {{ trimPrefix (printf "main-") (base .ITEM) | trimSuffix ".yaml" }}
+
+  _apply-machineconfig:
+    internal: true
+    desc: Apply bootstrap machineConfig to talos node
+    preconditions:
+      - which talosctl
+      - talosctl config info
+      - test -f "{{.FILENAME}}"
+    requires:
+      vars:
+        - HOSTNAME
+        - FILENAME
+    cmds:
+      - talosctl apply-config --nodes "{{.HOSTNAME}}" --file "{{.FILENAME}}" --insecure
